import {
  Vendor,
  Band,
  ChildRecord,
  SubscriptionPlan,
  Subscription,
  Registration,
  Payment,
  Commission,
  Payout,
  Incident,
  Enquiry,
  AppActivity,
  AppSettings,
} from '../types';

export const initialSettings: AppSettings = {
  officePhone: '+1 (800) 555-WE4U',
  officeEmail: 'support@we4you-contact.org',
  officeAddress: 'We 4 You Central Office, 400 Harmony Way, Suite 210',
  officeHours: 'Monday – Friday, 8:00 AM – 6:00 PM EST',
  availableLanguages: ['English', 'Spanish', 'French', 'Arabic'],
  directPurchaseEnabled: true,
  allowPhotoUpload: true,
  defaultCommissionPercentage: 15,
  defaultCommissionFixed: 10,
  simulationNote: 'Frontend Demonstration Mode — No actual live transmissions or payments are processed.',
};

export const initialVendors: Vendor[] = [
  {
    id: 'VND-001',
    shopName: 'KinderBloom Baby & Kids',
    branch: 'Metro Centre Mall',
    contactPerson: 'Sarah Jenkins',
    telephone: '+1 (555) 234-8901',
    address: '100 Metro Mall Way, Suite 14',
    isActive: true,
    commissionRate: 15,
    commissionType: 'percentage',
    createdAt: '2026-01-15',
  },
  {
    id: 'VND-002',
    shopName: 'Little Steps Family Care',
    branch: 'Westfield Galleria',
    contactPerson: 'David Miller',
    telephone: '+1 (555) 345-6789',
    address: '450 Galleria Blvd, Level 2',
    isActive: true,
    commissionRate: 10,
    commissionType: 'fixed',
    createdAt: '2026-02-10',
  },
  {
    id: 'VND-003',
    shopName: 'Haven Family Outfitters',
    branch: 'High Street Arcade',
    contactPerson: 'Miriam Al-Hassan',
    telephone: '+1 (555) 456-7890',
    address: '78 High Street, Suite B',
    isActive: true,
    commissionRate: 15,
    commissionType: 'percentage',
    createdAt: '2026-03-01',
  },
  {
    id: 'VND-004',
    shopName: 'Tiny Wanderers Gear',
    branch: 'North Point Town Plaza',
    contactPerson: 'Robert Chen',
    telephone: '+1 (555) 567-8901',
    address: '920 North Point Pkwy',
    isActive: true,
    commissionRate: 12,
    commissionType: 'fixed',
    createdAt: '2026-04-12',
  },
  {
    id: 'VND-005',
    shopName: 'Sunlight Children’s Corner',
    branch: 'Harbor Point (Closed)',
    contactPerson: 'Amanda Ross',
    telephone: '+1 (555) 678-9012',
    address: '32 Harbor Wharf Road',
    isActive: false, // Inactive fixture for demonstrating filter & historical persistence
    commissionRate: 10,
    commissionType: 'fixed',
    createdAt: '2025-11-20',
  },
];

export const initialPlans: SubscriptionPlan[] = [
  {
    id: 'PLAN-ANNUAL',
    name: 'Annual Protection Plan',
    durationMonths: 12,
    priceFormatted: '$29.00 / year (Sample)',
    priceAmount: 29,
    currency: 'USD',
    description: '12 months of dedicated 24/7 office emergency contact intermediary coverage and reference monitoring for any individual.',
    isActive: true,
    isProvisional: false,
    features: [
      'Dedicated office telephone contact coordination',
      'Private emergency contact reference routing',
      'Up to 2 registered secondary emergency contacts',
      'Prompt office relay if wearer is reported or assistance is requested',
      'Sample commercial terms — demonstration only'
    ],
  },
  {
    id: 'PLAN-2YEAR',
    name: 'Two-Year Extended Plan',
    durationMonths: 24,
    priceFormatted: '$49.00 / 2 years (Sample)',
    priceAmount: 49,
    currency: 'USD',
    description: 'Two full years of continuous reassurance and uninterrupted emergency intermediary service.',
    isActive: true,
    isProvisional: false,
    features: [
      'All Annual Protection benefits for 24 months',
      'Priority emergency contact record updates anytime',
      'Simplified renewal without band re-registration',
      'Office confirmation reports on request',
      'Sample commercial terms — demonstration only'
    ],
  },
  {
    id: 'PLAN-GUARDIAN-PLUS',
    name: 'Family & Care Plus (Provisional)',
    durationMonths: 36,
    priceFormatted: 'Pricing to be confirmed',
    priceAmount: 0,
    currency: 'USD',
    description: 'Proposed multi-year subscription with flexible multi-contact emergency notifications.',
    isActive: true,
    isProvisional: true,
    features: [
      'Proposed multi-wearer linked family & care coverage',
      'Extended 36-month reference protection',
      'Quarterly contact detail verification reminders',
      'Terms and pricing subject to office confirmation'
    ],
  },
];

export const initialBands: Band[] = [
  {
    id: 'BND-001',
    referenceCode: 'W4Y-1082-M4',
    status: 'assigned',
    childId: 'CHD-001',
    vendorId: 'VND-001',
    assignedDate: '2026-02-14',
  },
  {
    id: 'BND-002',
    referenceCode: 'W4Y-2940-L1',
    status: 'assigned',
    childId: 'CHD-002',
    vendorId: 'VND-002',
    assignedDate: '2026-03-05',
  },
  {
    id: 'BND-003',
    referenceCode: 'W4Y-5832-B7',
    status: 'assigned',
    childId: 'CHD-003',
    vendorId: 'VND-003',
    assignedDate: '2026-04-18',
  },
  {
    id: 'BND-004',
    referenceCode: 'W4Y-7821-K9',
    status: 'available',
    vendorId: 'VND-001',
  },
  {
    id: 'BND-005',
    referenceCode: 'W4Y-9014-P3',
    status: 'available',
    vendorId: 'VND-002',
  },
  {
    id: 'BND-006',
    referenceCode: 'W4Y-3319-X5',
    status: 'available',
    vendorId: 'VND-004',
  },
  {
    id: 'BND-007',
    referenceCode: 'W4Y-4190-C8',
    status: 'lost',
    childId: 'CHD-004',
    vendorId: 'VND-001',
    replacementNotes: 'Guardian reported band lost at community center; replaced by W4Y-5832-B7.',
    replacedByCode: 'W4Y-5832-B7',
  },
  {
    id: 'BND-008',
    referenceCode: 'W4Y-6201-D4',
    status: 'retired',
    replacementNotes: 'Damaged clip during sports activity; retired from service inventory.',
    retiredDate: '2026-01-30',
  },
  {
    id: 'BND-009',
    referenceCode: 'W4Y-8833-Z1',
    status: 'available',
  },
];

export const initialChildren: ChildRecord[] = [
  {
    id: 'CHD-001',
    name: 'Lucas Vance (Sample)',
    ageRange: 'Child (4 – 6 years)',
    primaryGuardian: {
      fullName: 'Elena Vance',
      relationship: 'Mother',
      mobile: '+1 (555) 019-2834',
      email: 'elena.vance@sample.test',
      preferredLanguage: 'English',
      emergencyContact: {
        fullName: 'Marcus Vance',
        relationship: 'Father',
        telephone: '+1 (555) 019-2835',
      },
    },
    secondaryGuardians: [
      {
        fullName: 'Claire Vance',
        relationship: 'Grandmother',
        telephone: '+1 (555) 019-2839',
      },
    ],
    currentBandCode: 'W4Y-1082-M4',
    subscriptionId: 'SUB-001',
    vendorId: 'VND-001',
    purchaseDate: '2026-02-12',
    receiptRef: 'REC-2026-01',
    registeredDate: '2026-02-14',
    incidentsCount: 1,
  },
  {
    id: 'CHD-002',
    name: 'Arthur Pendelton (Sample)',
    ageRange: 'Senior (78 years, Memory Support)',
    primaryGuardian: {
      fullName: 'Claire Pendelton',
      relationship: 'Son / Daughter',
      mobile: '+1 (555) 018-9921',
      email: 'claire.pendelton@sample.test',
      preferredLanguage: 'English',
    },
    secondaryGuardians: [
      {
        fullName: 'Dr. Evelyn Reed',
        relationship: 'Caregiver / Nurse',
        telephone: '+1 (555) 018-9925',
      },
    ],
    currentBandCode: 'W4Y-2940-L1',
    subscriptionId: 'SUB-002',
    vendorId: 'VND-002',
    purchaseDate: '2026-03-02',
    receiptRef: 'REC-2026-02',
    registeredDate: '2026-03-05',
    incidentsCount: 0,
  },
  {
    id: 'CHD-003',
    name: 'Maya Lin (Sample)',
    ageRange: 'Adult (29 years, Outdoor Marathoner)',
    primaryGuardian: {
      fullName: 'David Lin',
      relationship: 'Spouse / Partner',
      mobile: '+1 (555) 014-4320',
      email: 'david.lin@sample.test',
      preferredLanguage: 'English',
      emergencyContact: {
        fullName: 'Priya Lin',
        relationship: 'Sister',
        telephone: '+1 (555) 014-4321',
      },
    },
    secondaryGuardians: [],
    currentBandCode: 'W4Y-5832-B7',
    subscriptionId: 'SUB-003',
    vendorId: 'VND-003',
    purchaseDate: '2026-04-15',
    receiptRef: 'REC-2026-03',
    registeredDate: '2026-04-18',
    incidentsCount: 0,
  },
];

export const initialSubscriptions: Subscription[] = [
  {
    id: 'SUB-001',
    childId: 'CHD-001',
    planId: 'PLAN-ANNUAL',
    status: 'active',
    startDate: '2026-02-14',
    expiryDate: '2027-02-14',
    paymentRef: 'REC-2026-01',
    renewalCount: 0,
  },
  {
    id: 'SUB-002',
    childId: 'CHD-002',
    planId: 'PLAN-2YEAR',
    status: 'active',
    startDate: '2026-03-05',
    expiryDate: '2028-03-05',
    paymentRef: 'REC-2026-02',
    renewalCount: 0,
  },
  {
    id: 'SUB-003',
    childId: 'CHD-003',
    planId: 'PLAN-ANNUAL',
    status: 'expiring_soon',
    startDate: '2025-10-01',
    expiryDate: '2026-10-01',
    paymentRef: 'REC-2026-03',
    renewalCount: 0,
  },
];

export const initialRegistrations: Registration[] = [
  {
    id: 'REG-2026-0182',
    referenceNumber: 'REG-2026-0182',
    submissionDate: '2026-09-17 14:22',
    status: 'pending_verification',
    paymentStatus: 'pending',
    guardian: {
      fullName: 'Sarah Watson',
      relationship: 'Mother',
      mobile: '+1 (555) 012-7819',
      email: 'sarah.w@sample.test',
      preferredLanguage: 'English',
      emergencyContact: {
        fullName: 'Thomas Watson',
        relationship: 'Father',
        telephone: '+1 (555) 012-7820',
      },
    },
    child: {
      name: 'Emma Watson (Sample)',
      ageRange: 'Child (4 – 6 years)',
    },
    bandCode: 'W4Y-7821-K9',
    vendorId: 'VND-001',
    planId: 'PLAN-ANNUAL',
    timeline: [
      {
        timestamp: '2026-09-17 14:22',
        actor: 'Applicant',
        action: 'Registration submitted online',
        notes: 'Awaiting office document verification and subscription payment receipt.',
      },
    ],
  },
  {
    id: 'REG-2026-0179',
    referenceNumber: 'REG-2026-0179',
    submissionDate: '2026-09-16 11:05',
    status: 'pending_verification',
    paymentStatus: 'verified',
    guardian: {
      fullName: 'Wei Chen',
      relationship: 'Caregiver / Nurse',
      mobile: '+1 (555) 016-5544',
      email: 'wei.chen@sample.test',
      preferredLanguage: 'English',
    },
    child: {
      name: 'Eleanor Chen (Sample)',
      ageRange: 'Senior (74 years)',
    },
    bandCode: 'W4Y-9014-P3',
    vendorId: 'VND-002',
    planId: 'PLAN-2YEAR',
    timeline: [
      {
        timestamp: '2026-09-16 11:05',
        actor: 'Applicant',
        action: 'Registration submitted online',
      },
      {
        timestamp: '2026-09-16 13:40',
        actor: 'Admin Staff',
        action: 'Manual Payment Verified',
        notes: 'Matched in-store receipt #REC-2026-106.',
      },
    ],
  },
  {
    id: 'REG-2026-0164',
    referenceNumber: 'REG-2026-0164',
    submissionDate: '2026-09-14 09:15',
    status: 'update_requested',
    paymentStatus: 'pending',
    guardian: {
      fullName: 'James Miller',
      relationship: 'Spouse / Partner',
      mobile: '+1 (555) 017-3321',
      email: 'james.miller@sample.test',
      preferredLanguage: 'English',
    },
    child: {
      name: 'Aria Miller (Sample)',
      ageRange: 'Adult (32 years, Medical Alert)',
    },
    bandCode: 'W4Y-3319-X5',
    vendorId: 'VND-004',
    planId: 'PLAN-ANNUAL',
    statusReason: 'Contact telephone requires verification of country code.',
    timeline: [
      {
        timestamp: '2026-09-14 09:15',
        actor: 'Applicant',
        action: 'Registration submitted',
      },
      {
        timestamp: '2026-09-14 10:30',
        actor: 'Office Staff',
        action: 'Information Update Requested',
        notes: 'Contacted emergency contact to clarify daytime telephone digits.',
      },
    ],
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'PAY-001',
    receiptRef: 'REC-2026-01',
    type: 'subscription',
    amount: 29.0,
    currency: 'USD',
    status: 'verified',
    paymentDate: '2026-02-14',
    registrationId: 'REG-HIST-01',
    childId: 'CHD-001',
    payerName: 'Elena Vance',
    notes: 'In-store manual payment confirmed with vendor voucher',
  },
  {
    id: 'PAY-002',
    receiptRef: 'REC-2026-02',
    type: 'subscription',
    amount: 49.0,
    currency: 'USD',
    status: 'verified',
    paymentDate: '2026-03-05',
    registrationId: 'REG-HIST-02',
    childId: 'CHD-002',
    payerName: 'David Lin',
    notes: 'Office counter receipt verification',
  },
  {
    id: 'PAY-003',
    receiptRef: 'REC-2026-106',
    type: 'subscription',
    amount: 49.0,
    currency: 'USD',
    status: 'verified',
    paymentDate: '2026-09-16',
    registrationId: 'REG-2026-0179',
    payerName: 'Wei Chen',
    notes: 'Simulated payment receipt confirmed',
  },
  {
    id: 'PAY-004',
    receiptRef: 'REC-2026-107',
    type: 'subscription',
    amount: 29.0,
    currency: 'USD',
    status: 'pending',
    paymentDate: '2026-09-17',
    registrationId: 'REG-2026-0182',
    payerName: 'Sarah Watson',
    notes: 'Pending customer offline transfer / store confirmation',
  },
];

export const initialCommissions: Commission[] = [
  {
    id: 'COM-001',
    vendorId: 'VND-001',
    saleId: 'PAY-001',
    registrationRef: 'REG-HIST-01',
    type: 'percentage',
    rate: 15,
    eligibleAmount: 29.0,
    commissionAmount: 4.35,
    status: 'paid',
    createdAt: '2026-02-14',
    payoutId: 'PAYOUT-2026-01',
  },
  {
    id: 'COM-002',
    vendorId: 'VND-002',
    saleId: 'PAY-002',
    registrationRef: 'REG-HIST-02',
    type: 'fixed',
    rate: 10,
    eligibleAmount: 49.0,
    commissionAmount: 10.0,
    status: 'approved',
    createdAt: '2026-03-05',
  },
  {
    id: 'COM-003',
    vendorId: 'VND-002',
    saleId: 'PAY-003',
    registrationRef: 'REG-2026-0179',
    type: 'fixed',
    rate: 10,
    eligibleAmount: 49.0,
    commissionAmount: 10.0,
    status: 'pending',
    createdAt: '2026-09-16',
  },
];

export const initialPayouts: Payout[] = [
  {
    id: 'PAYOUT-2026-01',
    payoutRef: 'PO-2026-001',
    vendorId: 'VND-001',
    commissionIds: ['COM-001'],
    totalAmount: 4.35,
    payoutDate: '2026-03-01',
    notes: 'Simulated February commission payout batch',
  },
];

export const initialIncidents: Incident[] = [
  {
    id: 'INC-2026-001',
    incidentRef: 'INC-2026-001',
    bandReference: 'W4Y-1082-M4',
    reportType: 'person_found',
    callerName: 'Officer J. Ramos',
    callerContact: '+1 (555) 789-0112',
    voluntaryLocation: 'Riverside Community Park near south walkway',
    notes: 'Individual wearing band was accompanied by park attendant. Contact requested.',
    status: 'contacting_guardian',
    createdAt: '2026-09-18 10:15',
    assignedStaff: 'Staff Coordinator Morgan',
    attempts: [
      {
        id: 'ATT-001',
        timestamp: '2026-09-18 10:18',
        staffName: 'Staff Coordinator Morgan',
        method: 'phone_call',
        contactTarget: 'Primary Contact (Elena Vance)',
        outcome: 'Phone rang, went to voicemail',
        notes: 'Left urgent, calm message explaining individual is safe with park officer.',
      },
      {
        id: 'ATT-002',
        timestamp: '2026-09-18 10:22',
        staffName: 'Staff Coordinator Morgan',
        method: 'phone_call',
        contactTarget: 'Emergency Contact (Marcus Vance)',
        outcome: 'Connected and spoken with contact',
        notes: 'Contact confirmed they are in the park 2 minutes away heading to south walkway.',
      },
    ],
  },
  {
    id: 'INC-2026-002',
    incidentRef: 'INC-2026-002',
    bandReference: 'W4Y-6201-D4',
    reportType: 'band_found_alone',
    callerName: 'High Street Arcade Lost & Found',
    callerContact: '+1 (555) 890-1234',
    voluntaryLocation: 'Arcade information desk, near entrance',
    notes: 'Band found on floor, clip detached.',
    status: 'resolved',
    createdAt: '2026-08-10 16:30',
    assignedStaff: 'Office Staff Taylor',
    resolvedAt: '2026-08-11 09:00',
    outcomeSummary: 'Emergency contact reached; confirmed wearer is safe at home. Replacement band issued.',
    attempts: [
      {
        id: 'ATT-003',
        timestamp: '2026-08-10 16:45',
        staffName: 'Office Staff Taylor',
        method: 'phone_call',
        contactTarget: 'Registered Contact',
        outcome: 'Spoke with contact',
        notes: 'Confirmed wearer is safe; old band retired.',
      },
    ],
  },
];

export const initialEnquiries: Enquiry[] = [
  {
    id: 'ENQ-001',
    name: 'Clara Oswald',
    email: 'clara.o@sample.test',
    topic: 'band_replacement',
    message: 'Hello, our band has a minor scuff on the clasp. How can we request a replacement band without losing our registration record?',
    createdAt: '2026-09-17 16:10',
    status: 'new',
  },
  {
    id: 'ENQ-002',
    name: 'Thomas Sterling',
    email: 'thomas.s@store-sample.test',
    topic: 'vendor_enquiry',
    message: 'We operate 3 health & family retail pharmacies in the northern district and would like to stock We 4 You bands for our customers.',
    createdAt: '2026-09-15 11:30',
    status: 'in_progress',
    notes: 'Staff sent vendor retail info pack.',
  },
  {
    id: 'ENQ-003',
    name: 'Maya Henderson',
    email: 'm.henderson@sample.test',
    topic: 'subscription',
    message: 'We are moving to a new apartment next month. How do we update our emergency numbers on the private registration?',
    createdAt: '2026-09-12 14:05',
    status: 'resolved',
    notes: 'Guided through phone verification procedure.',
  },
];

export const initialActivity: AppActivity[] = [
  {
    id: 'ACT-001',
    timestamp: '2026-09-18 10:22',
    actor: 'Staff Coordinator Morgan',
    actionType: 'Incident Update',
    description: 'Recorded telephone contact attempt for incident INC-2026-001 (Band W4Y-1082-M4).',
    entityType: 'incident',
    entityId: 'INC-2026-001',
  },
  {
    id: 'ACT-002',
    timestamp: '2026-09-17 14:22',
    actor: 'System',
    actionType: 'Registration Submitted',
    description: 'Received public registration REG-2026-0182 for Emma Watson.',
    entityType: 'registration',
    entityId: 'REG-2026-0182',
  },
  {
    id: 'ACT-003',
    timestamp: '2026-09-16 13:40',
    actor: 'Admin Staff',
    actionType: 'Payment Verified',
    description: 'Simulated payment verification for registration REG-2026-0179 ($49.00).',
    entityType: 'payment',
    entityId: 'PAY-003',
  },
  {
    id: 'ACT-004',
    timestamp: '2026-09-15 15:00',
    actor: 'Admin User',
    actionType: 'Vendor Updated',
    description: 'Set Sunlight Children’s Corner (Harbor Point) to inactive.',
    entityType: 'vendor',
    entityId: 'VND-005',
  },
];
